### PR TITLE
Fetches search results from movie db and firebase db

### PR DESCRIPTION
**Pull request by jordan-castelloe**
- accepts user search term and searches movie database
- grabs all user's movies from firebase and filters for the ones that match the search criteria
- should print both results (eventually)

### CODE REVIEW

**Comment by jordan-castelloe** [comment]
This DOESN'T WORK as stands but it's up if y'all want to mess around with it!

**Review by joechesney — APPROVED** [review]
great work

**Comment by jordan-castelloe** [comment]
OKAY IT WORKS. HELL YES. Here's what you should see when you test:

- Once your logged in, add a movie to your watch list
- Search for that movie
- You should see all the database results first and then (at the verrrry bottom) see the movie you added with two buttons ('mark as watched' and 'remove'). 
- It should look just like all the other movie cards EXCEPT for those two buttons

**Review by joechesney — APPROVED** [review]
super great job

**Pull request merged**
