### PR TITLE
Jc boilerplate html

### PR DESCRIPTION
**Pull request by jordan-castelloe**
- I basically converted the moqup to html and threw it in a handlebars template
- Right now this is a single, static template for EVERYTHING (not just the stuff that you see before you login)
- I will totally break this out into partials (probs later today) but I wanted to get a super basic version up ASAP in case anybody wants to work on it this morning
- This should have everything you need to target click events, etc.
- I used bootstrap because I'm lazy, but I'm not married to bootsrap at all and I'm happy to switch 
- I also tried to abide by a general rule of ONLY using classes to target styling and ONLY using id's to target with javascript, so you'll see stuff with the same class and ID and that's why (that way if we need to chance an ID to make the javascript more readable, we won't accidentally break our styling)
- The moqup shows a navbar up top with 'search my movies' and 'find new movies'. I'm pretty sure we decided to ditch that and just go with searchbars, but I couldn't remember so I stuck it in. Easy to delete- just let me know!
- Also, browserify was pitching a huge fucking fit about all of our empty functions and undeclared variables, so I had to comment out all of the js notes David and Mel wrote yesterday to get it to compile. (Grunt --force wouldn't work, it gave me a message that said 'TOO MANY ERRORS'.) I figure we can just un-comment as we get around to fleshing out each function.

### CODE REVIEW

**Comment by jordan-castelloe** [comment]
also, if you look at the files changed it looks like I added and deleted a ton of code but it was actually just commenting it out, it just reads as changes

**Comment by jordan-castelloe** [comment]
also, I used the CDN of bootstrap just to get us up and running so everybody doesn't have to install the module right now but once we're all in agreement maybe we should switch to the npm module?

**Review by joechesney — APPROVED** [review]
Looks freakin badass. Thanks!

**Review by DavidLarsKetch — APPROVED** [review]
:+1:

**Review by joechesney — APPROVED** [review]
super perf

**Pull request merged**
